//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ans.Net8.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ans.Net8.Common.Resources.Common", typeof(Common).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d MMMM.
        /// </summary>
        public static string Format_Date_ForCurrentYear {
            get {
                return ResourceManager.GetString("Format_Date_ForCurrentYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d MMMM yyyy&apos; г.&apos;.
        /// </summary>
        public static string Format_Date_ForFull {
            get {
                return ResourceManager.GetString("Format_Date_ForFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;сегодня&apos;.
        /// </summary>
        public static string Format_Date_ForToday {
            get {
                return ResourceManager.GetString("Format_Date_ForToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;завтра&apos;.
        /// </summary>
        public static string Format_Date_ForTomorrow {
            get {
                return ResourceManager.GetString("Format_Date_ForTomorrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;вчера&apos;.
        /// </summary>
        public static string Format_Date_ForYesterday {
            get {
                return ResourceManager.GetString("Format_Date_ForYesterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d MMMM yyyy&apos; г.&apos;.
        /// </summary>
        public static string Format_DateRange_Full {
            get {
                return ResourceManager.GetString("Format_DateRange_Full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %d.
        /// </summary>
        public static string Format_DateRange_WithinMonth {
            get {
                return ResourceManager.GetString("Format_DateRange_WithinMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d MMMM.
        /// </summary>
        public static string Format_DateRange_WithinYear {
            get {
                return ResourceManager.GetString("Format_DateRange_WithinYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %d.
        /// </summary>
        public static string Format_DateSpanOfMonth_First {
            get {
                return ResourceManager.GetString("Format_DateSpanOfMonth_First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d MMMM.
        /// </summary>
        public static string Format_DateSpanOfMonth_Second {
            get {
                return ResourceManager.GetString("Format_DateSpanOfMonth_Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d MMMM&apos; в &apos;H:mmmm.
        /// </summary>
        public static string Format_DateTime_ForCurrentYear {
            get {
                return ResourceManager.GetString("Format_DateTime_ForCurrentYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d MMMM yyyy&apos; г. в &apos;H:mmmm.
        /// </summary>
        public static string Format_DateTime_ForFull {
            get {
                return ResourceManager.GetString("Format_DateTime_ForFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;сегодня в &apos;H:mmmm.
        /// </summary>
        public static string Format_DateTime_ForToday {
            get {
                return ResourceManager.GetString("Format_DateTime_ForToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;завтра в &apos;H:mmmm.
        /// </summary>
        public static string Format_DateTime_ForTomorrow {
            get {
                return ResourceManager.GetString("Format_DateTime_ForTomorrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;вчера в &apos;H:mmmm.
        /// </summary>
        public static string Format_DateTime_ForYesterday {
            get {
                return ResourceManager.GetString("Format_DateTime_ForYesterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ### ### ### ###&apos; КБ&apos;.
        /// </summary>
        public static string Format_SizeKB {
            get {
                return ResourceManager.GetString("Format_SizeKB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to –все–.
        /// </summary>
        public static string Text_AllItems {
            get {
                return ResourceManager.GetString("Text_AllItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to –нет–.
        /// </summary>
        public static string Text_EmptyItem {
            get {
                return ResourceManager.GetString("Text_EmptyItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to никогда.
        /// </summary>
        public static string Text_Never {
            get {
                return ResourceManager.GetString("Text_Never", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нажмите любую клавишу для выхода.
        /// </summary>
        public static string Text_PressAnyKeyToExit {
            get {
                return ResourceManager.GetString("Text_PressAnyKeyToExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нажмите ESC для выхода.
        /// </summary>
        public static string Text_PressEscToExit {
            get {
                return ResourceManager.GetString("Text_PressEscToExit", resourceCulture);
            }
        }
    }
}
