//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ans.Net8.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ModelErrors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ModelErrors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ans.Net8.Common.Resources.ModelErrors", typeof(ModelErrors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неизвестная ошибка.
        /// </summary>
        public static string @__Unknow {
            get {
                return ResourceManager.GetString("__Unknow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значение не соответствует.
        /// </summary>
        public static string _CaptchaFail {
            get {
                return ResourceManager.GetString("_CaptchaFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Превышено количество параметров.
        /// </summary>
        public static string _ExceededParameters {
            get {
                return ResourceManager.GetString("_ExceededParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Размер файла не должен превышать {0} байт.
        /// </summary>
        public static string _FileSizeShouldNotExceed_TML {
            get {
                return ResourceManager.GetString("_FileSizeShouldNotExceed_TML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неподдерживаемый тип файла.
        /// </summary>
        public static string _InvalidFileType {
            get {
                return ResourceManager.GetString("_InvalidFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Объект содержить данные.
        /// </summary>
        public static string _ObjectContainsData {
            get {
                return ResourceManager.GetString("_ObjectContainsData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не должно быть позже {0}.
        /// </summary>
        public static string _RangeDate_Max_TML {
            get {
                return ResourceManager.GetString("_RangeDate_Max_TML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не должно быть раньше {0}.
        /// </summary>
        public static string _RangeDate_Min_TML {
            get {
                return ResourceManager.GetString("_RangeDate_Min_TML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не должно быть больше {0}.
        /// </summary>
        public static string _RangeNumber_Max_TML {
            get {
                return ResourceManager.GetString("_RangeNumber_Max_TML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не должно быть меньше {0}.
        /// </summary>
        public static string _RangeNumber_Min_TML {
            get {
                return ResourceManager.GetString("_RangeNumber_Min_TML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Требуется уникальное значение.
        /// </summary>
        public static string _RequiresAUniqueValue {
            get {
                return ResourceManager.GetString("_RequiresAUniqueValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Такой объект уже существует.
        /// </summary>
        public static string _SuchAnObjectExists {
            get {
                return ResourceManager.GetString("_SuchAnObjectExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка локального пути загрузки.
        /// </summary>
        public static string _UploadLocalPathError {
            get {
                return ResourceManager.GetString("_UploadLocalPathError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Попытка загрузить за один запрос несколько фрагментов одного файла.
        /// </summary>
        public static string _UploadMoreFragments {
            get {
                return ResourceManager.GetString("_UploadMoreFragments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтверждение не совпадает с исходным значением.
        /// </summary>
        public static string _ValueAndConfirmDoNotMatch {
            get {
                return ResourceManager.GetString("_ValueAndConfirmDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не должно содержать больше {1} символов.
        /// </summary>
        public static string MaxLength_TML {
            get {
                return ResourceManager.GetString("MaxLength_TML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не должно содержать меньше {1} символов.
        /// </summary>
        public static string MinLength_TML {
            get {
                return ResourceManager.GetString("MinLength_TML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значение не соответствует формату.
        /// </summary>
        public static string RegularExpression {
            get {
                return ResourceManager.GetString("RegularExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Требуется значение.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
    }
}
