//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ans.Net8.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Validation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Validation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ans.Net8.Common.Resources.Validation", typeof(Validation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не должно быть позже {0}.
        /// </summary>
        public static string Template_DataMaxValueLimit {
            get {
                return ResourceManager.GetString("Template_DataMaxValueLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не должно быть раньше {0}.
        /// </summary>
        public static string Template_DataMinValueLimit {
            get {
                return ResourceManager.GetString("Template_DataMinValueLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не должно содержать больше {0} символов.
        /// </summary>
        public static string Template_LengthMaxLimit {
            get {
                return ResourceManager.GetString("Template_LengthMaxLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не должно содержать меньше {0} символов.
        /// </summary>
        public static string Template_LengthMinLimit {
            get {
                return ResourceManager.GetString("Template_LengthMinLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не должно быть больше {0}.
        /// </summary>
        public static string Template_NumberMaxValueLimit {
            get {
                return ResourceManager.GetString("Template_NumberMaxValueLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не должно быть меньше {0}.
        /// </summary>
        public static string Template_NumberMinValueLimit {
            get {
                return ResourceManager.GetString("Template_NumberMinValueLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Объект содержит данные.
        /// </summary>
        public static string Text_ObjectContainsData {
            get {
                return ResourceManager.GetString("Text_ObjectContainsData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Требуется уникальное значение.
        /// </summary>
        public static string Text_RequiresAUniqueValue {
            get {
                return ResourceManager.GetString("Text_RequiresAUniqueValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Такой объект уже существует.
        /// </summary>
        public static string Text_SuchAnObjectExists {
            get {
                return ResourceManager.GetString("Text_SuchAnObjectExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтверждение не совпадает с исходным значением.
        /// </summary>
        public static string Text_ValueAndConfirmDoNotMatch {
            get {
                return ResourceManager.GetString("Text_ValueAndConfirmDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значение не соответствует формату.
        /// </summary>
        public static string Text_ValueDoesNotFit {
            get {
                return ResourceManager.GetString("Text_ValueDoesNotFit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Требуется значение.
        /// </summary>
        public static string Text_ValueIsRequired {
            get {
                return ResourceManager.GetString("Text_ValueIsRequired", resourceCulture);
            }
        }
    }
}
